name: continuum_robot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - jupyter
  - jupyterlab
  - ipywidgets
  - matplotlib
  - pip
  - pip:
    - symforce-opt
    - "-r requirements.txt"
