services:
  test:
    build:
      context: ..
      dockerfile: environment/docker/Dockerfile
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
    environment:
      - PYTHONPATH=/app
    command: conda run --no-capture-output -n continuum_robot pytest tests/

  jupyter:
    build:
      context: ..
      dockerfile: environment/docker/Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ../src:/home/jovyan/work/src
      - ../notebooks:/home/jovyan/work/notebooks
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: "start-notebook.sh --NotebookApp.token="
