version: '3.8'

services:
  continuum_robot:
    build:
      context: ..
      dockerfile: environment/docker/Dockerfile
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
    environment:
      - PYTHONPATH=/app
    command: conda run --no-capture-output -n continuum_robot pytest tests/
